spring.datasource.url=jdbc:mysql://192.168.2.110:33060/ownblogdb
spring.datasource.username=root
spring.datasource.password=Unapassword1234!

#propiedades hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto=update

