################################################################################

# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

# JDBC URL of the database.
spring.datasource.url=jdbc:postgresql://ec2-52-1-17-228.compute-1.amazonaws.com:5432/dcqjng9kaussoh
# Login username of the database.
spring.datasource.username=krdwekdnsrplkz
# Login password of the database.
spring.datasource.password=abaab45f5ee891fa5635052e795cafe6d37ac8149365a3d9def420ad4cd3448e

# JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)

# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Defaults to "create-drop" when using an embedded database and no schema manager was detected. Otherwise, defaults to "none".
spring.jpa.hibernate.ddl-auto=update
# Whether to enable logging of SQL statements.
spring.jpa.show-sql=true
